apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-datastore-microservice
spec:
  selector:
    matchLabels:
      app: training-datastore
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: training-datastore
    spec:
      containers:
        - name: training-datastore
          image: docker.35.238.247.144.nip.io:5000/training-datastore:latest
          # image: docker.io/asheeshgoja/training-datastore:latest@sha256:dc2366d51c8b3d46f902968c244261c465d7668720edf0f8dcc8827d8389c6a9
          # securityContext:
          # privileged: true
          env:
            - name: PORT
              value: "8080"
          volumeMounts:
            - name: volv
              mountPath: /data
            - name: secret-volume
              mountPath: /keys              
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: artifacts-registry-volm
        - name: secret-volume
          secret:
            secretName: ssh-keys-secret             
      nodeSelector:
        kubernetes.io/hostname : "agentnode-raspi1" 
---
apiVersion: v1
kind: Service
metadata:
  name: training-datastore-service
spec:
  type: NodePort
  selector:
    app: training-datastore
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
# training-datastore-service.architectsguide2aiot.svc.cluster.local
