apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-registry-microservice
  # namespace: kafka
spec:
  selector:
    matchLabels:
      app: model-registry
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: model-registry
    spec:
      containers:
        - name: model-registry
          image: docker.35.238.247.144.nip.io:5000/model-registry:latest
          # image: docker.io/asheeshgoja/model-registry:latest@sha256:dc2366d51c8b3d46f902968c244261c465d7668720edf0f8dcc8827d8389c6a9
          # securityContext:
          # privileged: true
          env:
            - name: PORT
              value: "8080"
          volumeMounts:
            - name: volv
              mountPath: /data
            - name: secret-volume
              mountPath: /keys              
      volumes:
        - name: volv
          persistentVolumeClaim:
            claimName: artifacts-registry-volm
        - name: secret-volume
          secret:
            secretName: ssh-keys-secret                   
      nodeSelector:
        kubernetes.io/hostname : "agentnode-raspi1"
---
apiVersion: v1
kind: Service
metadata:
  name: model-registry-service
spec:
  type: NodePort
  selector:
    app: model-registry
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
# model-registry-service.architectsguide2aiot.svc.cluster.local
