const char* reg_svr_pub_key= \
"-----BEGIN CERTIFICATE-----\n" \
"MIICSDCCAc6gAwIBAgIUDXRzo8SpZJeJqZmgNP1BpyllvHkwCgYIKoZIzj0EAwIw\n" \
"WzELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMQswCQYDVQQHDAJDQTERMA8GA1UE\n" \
"CgwIZ29qYS5vcmcxCzAJBgNVBAsMAmdvMRIwEAYDVQQDDAkxMC4wLjAuMzAwHhcN\n" \
"MjIwNTI2MDI1NTIwWhcNMzIwNTIzMDI1NTIwWjBbMQswCQYDVQQGEwJVUzELMAkG\n" \
"A1UECAwCQ0ExCzAJBgNVBAcMAkNBMREwDwYDVQQKDAhnb2phLm9yZzELMAkGA1UE\n" \
"CwwCZ28xEjAQBgNVBAMMCTEwLjAuMC4zMDB2MBAGByqGSM49AgEGBSuBBAAiA2IA\n" \
"BHALumEGH+r0UuvnolMVd8fuqRrntwXRc9oK+Dsfli+P1wMsXRR5hKnnAAXWzdhe\n" \
"UJqrxAbbObDabq503ReS0VlDbB8tM3Kp2outLXyATVZ/JW2VK0SVOaJoACEu9hiX\n" \
"B6NTMFEwHQYDVR0OBBYEFMXlo2/Ew1TJjNCnKiRnGTEYIdyPMB8GA1UdIwQYMBaA\n" \
"FMXlo2/Ew1TJjNCnKiRnGTEYIdyPMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0E\n" \
"AwIDaAAwZQIwLr50uPgVJMrWTZzzvKGEvULb0j4tt4xF8gdtCqnRVLwmmYx3doh3\n" \
"6iN0v4VgtP8PAjEA9IsguVc9hiq8r5scFqcDaq6frAPG2ZxhTuVNNOGzXx8nujWy\n" \
"G1+vzdD22p/5aFsX\n" \
"-----END CERTIFICATE-----\n" ;