apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker-deployment
  labels:
    app: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
        - name: broker-container
          # image: hivemq/hivemq-ce
          image: docker.35.238.247.144.nip.io:5000/go_amr64_mqtt_broker:latest
          # resources:
          #   limits:
          #     memory: "0.6Gi"
          #     cpu: "300m"
          #   requests:
          #     memory: "0.2Gi"
          #     cpu: "150m"
          ports:
            - containerPort: 1883
      nodeSelector:
        kubernetes.io/hostname: "agentnode-raspi1"
        # kubernetes.io/hostname : "agentnode-nvidia-jetson"
        # kubernetes.io/hostname : "kubecon-aiot-control-node"

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker-service
spec:
  type: NodePort
  selector:
    app: mqtt-broker
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 30005


# apiVersion: v1
# kind: Service
# metadata:
#   name: mqtt-broker-service
# spec:
#   selector:
#     app: mqtt-broker
#   type: LoadBalancer
#   ports:
#     - port: 1883
#       targetPort: 1883
#       nodePort: 30005
